spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
# ===================================================================
# 分布式文件系统FDFS配置
fdfs:
  so-timeout: 5000
  connect-timeout: 1000
  thumb-image:
    width: 150
    height: 150
  #TrackerList参数,支持多个
  tracker-list: 
    - 192.168.100.101:22122
    - 192.168.100.102:22122
#    - 10.88.104.233:22122
#    - 10.88.104.234:22122
# ===================================================================
