server:
  port: 8080

spring:
  datasource:
      druid:
        url: jdbc:mysql://localhost:3306/es_readbook?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: rico
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 10
        minIdle: 4
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        filters: stat,wall
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
        
        filter:
          stat:
            enabled: true
            db-type: mysql
            log-slow-sql: true
            slow-sql-millis: 500
            merge-sql: true
            connection-stack-trace-enable: true
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  elasticsearch:
    rest:
      uris: 
      - 192.168.100.101:9200
      - 192.168.100.102:9200
      - 192.168.100.103:9200
        
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  file:
    path: ./logs
    name: boot-mybatisplus.log
  level:
    root: INFO
    org:
      mybatis: debug
    com:
      baomidou:
        mybatisplus: debug      