spring:
  redis:
    host: localhost
    port: 6379
    password: deepdata$
    # Redis 连接超时时间（单位：毫秒）
    database: 0
#    timeout: 5000
    lettuce:
      pool:
        min-idle: 10
        max-idle: 50
        max-active: 100
        max-wait: 1000
  redis2:
    host: 192.168.100.16
    port: 6379
    password: deepdata$
    # Redis 连接超时时间（单位：毫秒）
    database: 0
#    timeout: 5000
    lettuce:
      pool:
        min-idle: 10
        max-idle: 50
        max-active: 100
        max-wait: 1000
        
