
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/tx_test?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&useCompression=true&useUnicode=true&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false
      username: rico
      password: 123456
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      validation-query: SELECT 1
      validation-query-timeout: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      keep-alive: false
      filters: stat,wall
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 1800000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: -1
  jackson:
    serialization:
      indent_output: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mybatis/mapper/*.xml
server:
  port: 8081
