server:
  port: 8888
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:file:~/data/transport_client;MODE=MYSQL;FORBID_CREATION=FALSE;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      connection-timeout: 30000
      idle-timeout: 300000
      maximum-pool-size: 10
      minimum-idle: 10
      max-lifetime: 1800000
      keepaliveTime: 0
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      auto-commit: true #默认true
    initialization-mode: embedded
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  jpa:
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        archive:
          scanner: org.hibernate.boot.archive.scan.internal.StandardScanner #解决新版Hibernate找不到hbm.xml文件问题
        show_sql: true
        format_sql: true
        ddl-auto: none
        jdbc.batch_size: 100
        order_inserts: true
        order_updates: true
        jdbc.time_zone: Asia/Shanghai
        generate_statistics: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
        entitymanager:
          class: org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean
          mappingDirectoryLocations: classpath:named-sql
        packagesToScan: com.loserico.jpa.entity
    hibernate:
      ddl-auto: none
  
  hibernate.query.mode: loose
  hibernate.query.cache: true
  hibernate.jdbc.batch_size: 100
