spring:
  mail:
#    host: smtp.163.com
    host: smtp.exmail.qq.com
    username: yuxuehua@rzhrt.com.cn
    password: uKug3uENj7DPZvk5
#    protocol: smtp
#    port: 465
#    username: ricoyu_521@163.com
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
            port: 465
