spring:
  mail:
#    host: smtp.163.com
    host: smtp.exmail.qq.com
#    username: ricoyu_521@163.com
    username: yuxuehua@rzhrt.com.cn
    password: F6JiGwNz45yWcgPr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true
