spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.100.11:4000/perf_test?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&useCompression=true&useUnicode=true&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false
      username: dev
      password: 123456
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      validation-query: SELECT 1
      validation-query-timeout: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      keep-alive: false
      filters: stat,wall
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 1800000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: -1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        archive:
          scanner: org.hibernate.boot.archive.scan.internal.StandardScanner #解决新版Hibernate找不到hbm.xml文件问题
        show_sql: true
        format_sql: true
        ddl-auto: none
        jdbc.batch_size: 100
        order_inserts: true
        order_updates: true
        jdbc.time_zone: Asia/Shanghai
        generate_statistics: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
        entitymanager:
          class: org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean
          mappingDirectoryLocations: classpath:named-sql
        packagesToScan: com.loserico.jpa.entity
        hibernate:
          ddl-auto: none
          format_sql: true
      show-sql: true
  
#  jackson:
#    serialization:
#      indent-output: true
