spring:
  main:
    web-application-type: NONE
  datasource:
    url: jdbc:mysql://localhost:3306/t00000?serverTimezone=Asia/Shanghai&useSSL=false&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&useCompression=true&useUnicode=true&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false
    username: rico
    password: 123456
    hikari:
      connection-timeout: 30000
      idle-timeout: 300000
      maximum-pool-size: 10
      minimum-idle: 10
      max-lifetime: 1800000
      keepaliveTime: 0
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      auto-commit: true #默认true
  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        archive:
          scanner: org.hibernate.boot.archive.scan.internal.StandardScanner #解决新版Hibernate找不到hbm.xml文件问题
#        show_sql: true
        format_sql: true
        ddl-auto: none
        jdbc.batch_size: 100
        order_inserts: true
        order_updates: true
        jdbc.time_zone: Asia/Shanghai
        generate_statistics: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
        entitymanager:
          class: org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean
          mappingDirectoryLocations: classpath:named-sql
        packagesToScan: com.loserico.jpa.entity
    show-sql: true

hibernate.query.mode: loose
hibernate.query.cache: true
#hibernate.jdbc.batch_size: 10
hibernate:
  query.mode: loose
  query.cache: true
  order_inserts: true
  order_updates: true
  jdbc:
    batch_size: 10
